fix error

diff --git a/bin/autonity b/bin/autonity
--- a/bin/autonity
+++ b/bin/autonity
@@ -1,152 +1,236 @@
 #!/bin/bash
 
-AUT=$(which aut)
-VALIDATORADDRESS=$(grep 'validator=' $HOME/.autrc | cut -d'=' -f2)
+
+AUT=$(command -v aut)
+AUTONITY=$(command -v autonity)
+VALIDATORADDRESS=$(grep validator= "$HOME/.autrc" | cut -d'=' -f2)
 KEFILE1="$HOME/.autonity/keystore/oracle.key"
 KEFILE2="$HOME/.autonity/keystore/treasury.key"
 TOOLS="$HOME/autonity/tools"
-AUTONITY=$(which autonity)
-CAX="$TOOLS/cax"
+CAX="$HOME/autonity/tools/cax"
+DOCKER_COMPOSE="$HOME/autonity/docker-compose.yml"
 
 
 display_help() {
-    cat << EOF
+    cat <<EOF
 Usage: autonity <command> <subcommand>
 
 Available commands:
-  validator           - Command for interacting with Validator management
-  wallet              - Command for interacting with Wallet management
-  node                - Command for interacting with Node management
-  oracle              - Command for interacting with Oracle server management
-  cax                 - Command for interacting with CAX
-  help                - Display help menu
-
+  validator   - Validator management
+  wallet      - Wallet management
+  node        - Node management
+  oracle      - Oracle server management
+  cax         - CAX management
+  help        - Display help menu
 EOF
     exit 0
 }
 
 
-[[ $# -eq 0 ]] && display_help && exit 1
+if [[ $# -eq 0 ]]; then
+    display_help
+    exit 1
+fi
 
 
-case "$1" in
-    validator)
-        case "$2" in
-            setup)
-                while true; do
-                    clear
-                    echo "===== Validator Management Menu ====="
-                    options=("Create Validator" "Bond & Unbond Validator" "Pause & Reactivate Validator" "Change Commission Rate" "Exit")
-                    PS3="Enter your choice (1-${#options[@]}): "
-                    select opt in "${options[@]}"; do
-                        case $REPLY in
-                            1) $TOOLS/create-validator.sh ;;
-                            2) $TOOLS/bond-unbond-validator.sh ;;
-                            3) $TOOLS/pause-reactivate-validator.sh ;;
-                            4) $TOOLS/change-validator-commission.sh ;;
-                            5) echo "Exiting..." && exit 0 ;;
-                            *) echo "Invalid choice. Please enter a number between 1-5." ;;
-                        esac
-                        break
-                    done
-                    read -p "Press Enter to continue..."
-                done
-                ;;
-            info) echo "Validator Info" && $TOOLS/validatorinfo.sh ;;
-            list) echo "Validator List" && $AUT validator list | awk '{print NR".",$0}' ;;
-            seat) [[ "$3" == "active" ]] && echo "Seat Active Validators List" && $TOOLS/committe.sh ;;
-            committe) 
-                echo "Check if your validator is in the Seat Active"
-                $AUT protocol get-committee | grep $VALIDATORADDRESS && echo "Your validator is in the committee" || echo "Your validator is not in the committee"
-                ;;
-            help|*) $AUTONITY validator help ;;
-        esac
-        ;;
-    wallet)
-        case "$2" in
-            management)
-                while true; do
-                    clear
-                    echo "===== Wallet Management Menu ====="
-                    options=("Create Signature registration for game" "Create Signature for Validator onboarded" "Create transaction" "Create wallet" "Create backup wallet" "Exit")
-                    PS3="Enter your choice (1-${#options[@]}): "
-                    select opt in "${options[@]}"; do
-                        case $REPLY in
-                            1) $TOOLS/signature.sh ;;
-                            2) $TOOLS/valonboarded.sh ;;
-                            3) $TOOLS/tx.sh ;;
-                            4) $TOOLS/create-other-wallet.sh ;;
-                            5) $TOOLS/backup-wallet.sh ;;
-                            6) echo "Exiting..." && exit 0 ;;
-                            *) echo "Invalid choice. Please enter a number between 1-6." ;;
-                        esac
-                        break
-                    done
-                    read -p "Press Enter to continue..."
-                done
-                ;;
-            info) echo "Wallet Info" && $TOOLS/wallet-info.sh ;;
-            list) echo "Wallet List" && $AUT account list ;;
-            help|*) $AUTONITY wallet help ;;
-        esac
-        ;;
-    node)
-        case "$2" in
-            start) echo "Start Node" && docker-compose -f ~/autonity/docker-compose.yml up -d autonity ;;
-            logs) echo "Node Logs" && docker logs -f --tail=20 autonity ;;
-            epoch) echo "Node Epoch" && $TOOLS/epoch.sh ;;
-            sync) echo "Node Sync" && $AUT node info | jq '{eth_blockNumber, eth_syncing}' ;;
-            update) 
-                echo "Node Update"
-                docker-compose -f $HOME/autonity/docker-compose.yml pull autonity
-                docker-compose -f $HOME/autonity/docker-compose.yml up -d autonity
-                ;;
-            stop) echo "Stop Node" && docker stop autonity ;;
-            restart) echo "Restart Node" && docker restart autonity ;;
-            help|*) $AUTONITY node help ;;
-        esac
-        ;;
-    oracle)
-        case "$2" in
-            start) echo "Start Oracle" && docker-compose -f ~/autonity/docker-compose.yml up -d oracle ;;
-            logs) echo "Oracle Logs" && docker logs -f --tail=20 oracle ;;
-            stop) echo "Stop Oracle" && docker stop oracle ;;
-            restart) echo "Restart Oracle" && docker restart oracle ;;
-            update) 
-                echo "Oracle Update"
-                docker-compose -f $HOME/autonity/docker-compose.yml pull oracle
-                docker-compose -f $HOME/autonity/docker-compose.yml up -d oracle
-                ;;
-            help|*) $AUTONITY oracle help ;;
-        esac
-        ;;
-    cax)
-        case "$2" in
-            menu)
-                while true; do
-                    clear
-                    echo "===== CAX Management Menu ====="
-                    options=("Create Api Key" "Check Balance" "Place Order" "Cancel Order" "Withdraw" "Exit")
-                    PS3="Enter your choice (1-${#options[@]}): "
-                    select opt in "${options[@]}"; do
-                        case $REPLY in
-                            1) $CAX/generate-api.sh ;;
-                            2) $CAX/check-balance.sh ;;
-                            3) $CAX/order.sh ;;
-                            4) $CAX/cancel-order.sh ;;
-                            5) $CAX/withdraw.sh ;;
-                            6) echo "Exiting..." && exit 0 ;;
-                            *) echo "Invalid choice. Please enter a number between 1-6." ;;
-                        esac
-                        break
-                    done
-                    read -p "Press Enter to continue..."
-                done
-                ;;
-            help|*) $AUTONITY cax help ;;
-        esac
-        ;;
-    help|*) display_help ;;
-esac
+if [[ "$1" == "validator" ]]; then
+    case "$2" in
+        setup)
+            while true; do
+                clear
+                cat <<EOF
+===== Validator Management Menu =====
+1. Create Validator
+2. Bond & Unbond Validator
+3. Pause & Reactivate Validator
+4. Change Commission Rate
+5. Exit
+======================================
+EOF
+                read -p "Enter your choice (1-5): " choice
+
+                case $choice in
+                    1) $TOOLS/create-validator.sh ;;
+                    2) $TOOLS/bond-unbond-validator.sh ;;
+                    3) $TOOLS/pause-reactivate-validator.sh ;;
+                    4) $TOOLS/change-validator-commission.sh ;;
+                    5) echo "Exiting..." && exit 0 ;;
+                    *) echo "Invalid choice. Please enter a number between 1 and 5." ;;
+                esac
+                read -p "Press Enter to continue..."
+            done
+            ;;
+        info) echo "Validator Info" && $TOOLS/validatorinfo.sh ;;
+        list) echo "Validator List" && $AUT validator list | awk '{print NR".",$0}' ;;
+        seat)
+            if [[ "$3" == "active" ]]; then
+                echo "Seat Active Validators List"
+                $TOOLS/committe.sh
+            else
+                echo "Invalid subcommand. Please use 'active' with 'seat'."
+            fi
+            ;;
+        committe)
+            echo "Check if your validator is in the Seat Active"
+            $AUT protocol get-committee | grep "$VALIDATORADDRESS" && echo "Your validator is in the committee" || echo "Your validator is not in the committee"
+            ;;
+        help)
+            cat <<EOF
+Usage: autonity validator <subcommand>
+
+Available subcommands:
+  setup       - Validator setup
+  info        - Display validator info
+  list        - List all validators
+  seat active - Check active seats
+  committe    - Check if your validator is in the active seats
+  help        - Display help menu
+EOF
+            ;;
+        *) $AUTONITY validator help ;;
+    esac
+
+elif [[ "$1" == "wallet" ]]; then
+    case "$2" in
+        management)
+            while true; do
+                clear
+                cat <<EOF
+===== Wallet Management Menu =====
+1. Create Signature registration for game
+2. Create Signature for Validator onboarded
+3. Create transaction
+4. Create wallet
+5. Create backup wallet
+6. Exit
+=====================================
+EOF
+                read -p "Enter your choice (1-6): " choice
+
+                case $choice in
+                    1) $TOOLS/signature.sh ;;
+                    2) $TOOLS/valonboarded.sh ;;
+                    3) $TOOLS/tx.sh ;;
+                    4) $TOOLS/create-other-wallet.sh ;;
+                    5) $TOOLS/backup-wallet.sh ;;
+                    6) echo "Exiting..." && exit 0 ;;
+                    *) echo "Invalid choice. Please enter a number between 1 and 6." ;;
+                esac
+                read -p "Press Enter to continue..."
+            done
+            ;;
+        info) echo "Wallet Info" && echo "---------------------------------------------------------" && $TOOLS/wallet-info.sh ;;
+        list) echo "Wallet List" && $AUT account list ;;
+        help)
+            cat <<EOF
+Usage: autonity wallet <subcommand>
+
+Available subcommands:
+  management  - Wallet management
+  Info        - Check wallet details
+  list        - List all wallets
+  help        - Display help menu
+EOF
+            ;;
+        *) $AUTONITY wallet help ;;
+    esac
+
+elif [[ "$1" == "node" ]]; then
+    case "$2" in
+        start) echo "Start Node" && docker compose -f "$DOCKER_COMPOSE" up -d autonity ;;
+        logs) echo "Node Logs" && docker logs -f --tail=20 autonity ;;
+        epoch) echo "Node Epoch" && $TOOLS/epoch.sh ;;
+        sync) echo "Node Sync" && $AUT node info | jq '{eth_blockNumber, eth_syncing}' ;;
+        update) echo "Node Update" && docker compose -f "$DOCKER_COMPOSE" pull autonity && docker compose -f "$DOCKER_COMPOSE" up -d autonity ;;
+        stop) echo "Stop Node" && docker stop autonity ;;
+        restart) echo "Restart Node" && docker restart autonity ;;
+        help)
+            cat <<EOF
+Usage: autonity node <subcommand>
+
+Available subcommands:
+  start   - Start node
+  stop    - Stop node
+  restart - Restart node
+  logs    - Display node logs
+  epoch   - Display epoch
+  sync    - Display sync status
+  update  - Update node
+  help    - Display help menu
+EOF
+            ;;
+        *) $AUTONITY node help ;;
+    esac
+
+elif [[ "$1" == "oracle" ]]; then
+    case "$2" in
+        start) echo "Start Oracle" && docker compose -f "$DOCKER_COMPOSE" up -d oracle ;;
+        logs) echo "Oracle Logs" && docker logs -f --tail=20 oracle ;;
+        stop) echo "Stop Oracle" && docker stop oracle ;;
+        restart) echo "Restart Oracle" && docker restart oracle ;;
+        update) echo "Oracle Update" && docker compose -f "$DOCKER_COMPOSE" pull oracle && docker compose -f "$DOCKER_COMPOSE" up -d oracle ;;
+        help)
+            cat <<EOF
+Usage: autonity oracle <subcommand>
+
+Available subcommands:
+  start   - Start oracle
+  stop    - Stop oracle
+  restart - Restart oracle
+  logs    - Check oracle logs
+  update  - Update oracle
+  help    - Display help menu
+EOF
+            ;;
+        *) $AUTONITY oracle help ;;
+    esac
+
+elif [[ "$1" == "cax" ]]; then
+    case "$2" in
+        menu)
+            while true; do
+                clear
+                cat <<EOF
+===== CAX Management Menu =====
+1. Create Api Key
+2. Check Balance
+3. Place Order
+4. Cancel Order
+5. Withdraw
+6. Exit
+=====================================
+EOF
+                read -p "Enter your choice (1-6): " choice
+
+                case $choice in
+                    1) $CAX/generate-api.sh ;;
+                    2) $CAX/check-balance.sh ;;
+                    3) $CAX/order.sh ;;
+                    4) $CAX/cancel-order.sh ;;
+                    5) $CAX/withdraw.sh ;;
+                    6) echo "Exiting..." && exit 0 ;;
+                    *) echo "Invalid choice. Please enter a number between 1 and 6." ;;
+                esac
+                read -p "Press Enter to continue..."
+            done
+            ;;
+        help)
+            cat <<EOF
+Usage: autonity cax <subcommand>
+
+Available subcommands:
+  menu  - CAX Management Menu
+  help  - Display help menu
+EOF
+            ;;
+        *) $AUTONITY cax help ;;
+    esac
+
+elif [[ "$1" == "help" ]]; then
+    display_help
+else
+    echo "Invalid command"
+    display_help
+fi
 
 exit 0
